### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-2-entrevista-ka194#1]
[ENTREVISTA (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-ka194/files/12554386/ENTREVISTA.1.pdf)

**Comment by Alvaro2-0** [comment]
17/20
Faltas de ortografía.
Checar el espaciado.

**Comment by josealfredo79** [comment]
Revisado...
